### ISSUE TITLE
Custom Chest

### ISSUE THREAD

**Issue by chenzirui001** [xia-mc/Raven-bS#12]
![捕获](https://github.com/xia-mc/Raven-bS/assets/102465358/1dc67dd7-ca4d-466b-b8b5-871782da7b61)
Enabling "CostomChest" and then enabling InvManager will cause the game to crash
[crash-2024-06-26_07.03.22-client.txt](https://github.com/user-attachments/files/15980267/crash-2024-06-26_07.03.22-client.txt)

**Comment by xia-mc** [comment]
Fixed in [Release 1.6.1](https://github.com/xia-mc/Raven-bS/releases/tag/b1.6.1)
