### ISSUE TITLE
autoclicker being silly ;3;3;3;3333;3;33

### ISSUE THREAD

**Issue by larryngton** [xia-mc/Raven-bS#13]
autoclicker's right click option left clicks instead

**Comment by larryngton** [comment]
also autoclicker attacks on post now...
thanks for the ban

**Comment by xia-mc** [comment]
I'm sooooo sorry;;; this is a serious bug and I'll fix it and test it more before releasing the version!

**Comment by xia-mc** [comment]
Fixed in [Release 1.6.2](https://github.com/xia-mc/Raven-bS/releases/tag/b1.6.2)
I'm sorry..

**Comment by larryngton** [comment]
> I'm sooooo sorry;;; this is a serious bug and I'll fix it, and test more before releasing any version!

thank god I got banned on BMC and not on any good server 💀

**Comment by xia-mc** [comment]
> > I'm sooooo sorry;;; this is a serious bug and I'll fix it, and test more before releasing any version!
> 
> thank god I got banned on BMC and not on any good server 💀

Hypixel just doesn't check xd
