### ISSUE TITLE
The list of modules is too high

### ISSUE THREAD

**Issue by chenzirui001** [xia-mc/Raven-bS#15]
![捕获](https://github.com/xia-mc/Raven-bS/assets/102465358/ed43cccd-1284-42a8-8955-9b1ed69dbb70)

**Comment by xia-mc** [comment]
Yes, its a problem..

**Comment by aoehakDoc** [comment]
maybe add scrolling into the gui

**Comment by KgDW** [comment]
Scrolling has been added.
