### ISSUE TITLE
Reach→Hit through blocks

### ISSUE THREAD

**Issue by chenzirui001** [xia-mc/Raven-bS#17]
尝试隔墙攻击实体或者直接攻击物品展示框(带有物品)会导致游戏崩溃
![捕获 PNG2](https://github.com/xia-mc/Raven-bS/assets/102465358/d1714246-bfce-40b1-a0b3-85163d9a17e6)

**Comment by chenzirui001** [comment]
[crash-2024-06-30_06.33.37-client.txt](https://github.com/user-attachments/files/16042359/crash-2024-06-30_06.33.37-client.txt)

**Comment by xia-mc** [comment]
能看看你的FastMine设定吗？

**Comment by xia-mc** [comment]
我觉得我知道为什么了..下个版本修复

**Comment by xia-mc** [comment]
已在[Release 1.8.0](https://github.com/xia-mc/Raven-bS/releases/tag/b1.8.0)修复
