### ISSUE TITLE
[手机运行]未知原因的游戏崩溃

### ISSUE THREAD

**Issue by chenzirui001** [xia-mc/Raven-bS#23]
![Screenshot_2024-07-04-06-02-36-487_com tungsten fcl](https://github.com/xia-mc/Raven-bS/assets/102465358/fab18630-a556-4ce9-866a-3187c2c67ced)
![Screenshot_2024-07-04-05-58-28-487_com tungsten fcl](https://github.com/xia-mc/Raven-bS/assets/102465358/af56a848-e897-435a-94dd-f5d10581bdf6)
![Screenshot_2024-07-04-06-02-56-913_com tungsten fcl-edit](https://github.com/xia-mc/Raven-bS/assets/102465358/d88f61bf-a36c-4e10-bc73-cd305fd79631)
[crash-2024-07-04_06.04.33-client.txt](https://github.com/user-attachments/files/16091226/crash-2024-07-04_06.04.33-client.txt)
见到第二张图片(红地毯)的时候游戏会直接崩溃,当时应该是踩在了上面
其他模组(包括optfine)都已去除

**Comment by chenzirui001** [comment]
补充:电脑端似乎没有这个情况

**Comment by xia-mc** [comment]
Yes, it's animation issue, i will fix it

**Comment by xia-mc** [comment]
fixed in [1.10.1](https://github.com/xia-mc/Raven-bS/releases/tag/v1.10.1)
