### ISSUE TITLE
Slowly walking on Feather Client 

### ISSUE THREAD

**Issue by el1anbtw** [xia-mc/Raven-bS#3]
Can you please correct this error, it was often mentioned in this client's discord. It is related to the fact that mixins are not configured completely correctly, namely the file PlayerSP, and line of code where the game speed is adjusted.

**Comment by xia-mc** [comment]
this bug has been fixed in [Release 1.1.1](https://github.com/xia-mc/Raven-bS/releases/tag/b1.1.1).
