### ISSUE TITLE
Existing shortcomings and potential proposals 

### ISSUE THREAD

**Issue by el1anbtw** [xia-mc/Raven-bS#4]
Function: "RodAimbot" absolutely doesn’t work, no matter what settings I try, no matter what servers or single player I’m on, it doesn’t work.

Function: "FakeLag" needs changes, because at the moment it is almost impossible to use it.

Function: "WTap" I’m not entirely sure, but I have a feeling that it doesn’t work at all, no matter what settings I set, even if there’s a 100% chance, nothing happens anyway.

Potential proposals for implementation:
1) HitSelect – chooses the best time to hit
2) Backtrack – *brings the enemy back*
3) Ladder Clutch – places a block and a ladder on it when falling, so as not to take damage from the fall, if there is a block on which you can place a ladder, then only places a ladder

**Comment by xia-mc** [comment]
- RodAimBot: already known, but has no plan to fix it.
- Fakelag: will add new Dynamic mode in next release.
- WTap: it just stop sprinting on attack.. works more like superkb, not wtap.

- HitSelect: add in next release.
- Backtrack: reach 3.3 is better
- Ladder Clutch: nofall blink mode is better

**Comment by el1anbtw** [comment]
> * Backtrack: reach 3.3 is better
> * Ladder Clutch: nofall blink mode is better

Reach detected on many servers, so I suggest this particular function
Also NoFall, many servers are trying or have already fixed this problem, based on this I propose another function, but thanks for the quick response!

**Comment by xia-mc** [comment]
new Fakelag, WTap(Super Knockback), HitSelect has been add in [Release b1.2.0-pre1](https://github.com/xia-mc/Raven-bS/releases/tag/b1.2.0-pre1).
can someone test them in Hypixel :3
