### ISSUE TITLE
Vanilla ab

### ISSUE THREAD

**Issue by VeensCal** [xia-mc/Raven-bS#7]
Vanilla ab is a bug when I hit a player and kill and disable the module it doesn't unblock it's a bug

**Comment by xia-mc** [comment]
I'm sorry I can't reproduce it... Can you provide a video or some screen shots?

**Comment by VeensCal** [comment]
Ok

**Comment by VeensCal** [comment]
![Uploading Screenshot_2024-06-19-21-51-30-23_99c04817c0de5652397fc8b56c3b3817.jpg…]()

**Comment by VeensCal** [comment]
![Screenshot_2024-06-19-21-51-30-23_99c04817c0de5652397fc8b56c3b3817](https://github.com/xia-mc/Raven-bS/assets/157549746/48892650-07f4-4ffb-8b1f-8d6f9443b0b5

**Comment by VeensCal** [comment]
![Screenshot_2024-06-19-21-52-57-00_99c04817c0de5652397fc8b56c3b3817](https://github.com/xia-mc/Raven-bS/assets/157549746/86fe541a-9753-4ffd-a7e1-18649485b22a)

**Comment by VeensCal** [comment]
Here @xia-mc I can't record

**Comment by VeensCal** [comment]
Make a hotfix

**Comment by VeensCal** [comment]
I can't record so I can use screenshot

**Comment by VeensCal** [comment]
@xia-mc

**Comment by xia-mc** [comment]
Yes
